project:
  type: book

book:
  title: "Bacterial filamentation: a bet for survival in stressful environments"
  author:
    - name: "Jesús Vélez Santiago"
      orcid: 0000-0001-5128-3838
      url: https://jvelezmagic.com
      affiliations:
        - name: Center for Genomic Sciences - National Autonomous University of Mexico
    - name: "Rafael Peña-Miller"
      orcid: 0000-0002-2767-0640
      affiliations:
        - name: Center for Genomic Sciences - National Autonomous University of Mexico
      url: http://www.penamiller.com/lab/ 
  date: today
  search: true
  repo-url: https://github.com/jvelezmagic/bacterial-filamentation-research
  repo-actions: [source, issue, edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]
  chapters:
    - index.qmd
    - 00-introduction.qmd
    - 01-image-processing.qmd
    - 02-experiment-analysis.qmd
    - 03-model-analysis.qmd
    - 04-discussion.qmd
    - 98-appendices.qmd
    - references.qmd
  comments:
    hypothesis: true
  cover-image: bacterial-filamentation-cover.png

bibliography: [references.bib, project-general-packages.bib, project-R-packages.bib]

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"
    out.width: "100%"

format:
  html:
    theme:
        light: cosmo
        dark: darkly
    code-tools: true
    execute:
        echo: false
        warning: false
    toc: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    execute:
        echo: false
        warning: false
    toc: true
    toc-depth: 4
    lof: true
    lot: true
    geometry: 
      - left=2.5cm
      - right=2.5cm
      - heightrounded
    colorlinks: true
    papersize: a4
    link-citations: true
    fontsize: 12pt
    fig-pos: H
    dpi: 600
    fig-width: 8
    fig-height: 6
    
editor: visual
