project:
  type: book

book:
  title: "Bacterial filamentation: a bet for survival in stressful environments"
  author: "Jesús Vélez Santiago"
  date: "8/8/2022"
  chapters:
    - index.qmd
    - 00-introduction.qmd
    - 01-image-processing.qmd
    - 02-experiment-analysis.qmd
    - 03-model-analysis.qmd
    - 04-discussion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

