project:
  type: book

book:
  title: "Bacterial filamentation: a bet for survival in stressful environments"
  author: "Jesús Vélez Santiago"
  date: today
  search: true
  repo-url: https://github.com/jvelezmagic/bacterial-filamentation-research
  repo-actions: [source, issue, edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]
  chapters:
    - index.qmd
    - 00-introduction.qmd
    - 01-image-processing.qmd
    - 02-experiment-analysis.qmd
    - 03-model-analysis.qmd
    - 04-discussion.qmd
    - 98-appendices.qmd
    - references.qmd
  comments:
    hypothesis: true

bibliography: [references.bib, project-general-packages.bib, project-R-packages.bib]

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"
    out.width: "100%"

format:
  html:
    theme:
        light: cosmo
        dark: darkly
    code-tools: true
    execute:
        echo: false
        warning: false
    toc: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    execute:
        echo: false
        warning: false
    toc: true
    toc-depth: 4
    lof: true
    lot: true
    geometry: 
      - left=2.5cm
      - right=2.5cm
      - heightrounded
    colorlinks: true
    papersize: a4
    link-citations: true
    fontsize: 12pt
    fig-pos: H
    dpi: 600
    fig-width: 8
    fig-height: 6
    
editor: visual
